#!/usr/bin/php
<?
set_include_path("../include");
require("header.inc.php");

if (!Z_ENV_DEV_SITE) {
	die("Test setup script can be run only on dev sites\n");
}

Zotero_DB::query("DELETE FROM syncProcesses");
Zotero_DB::query("DELETE FROM syncQueue");
Zotero_DB::query("DELETE FROM libraries WHERE libraryID>3");
Zotero_DB::query("DELETE FROM zotero_www_test.users WHERE userID>2");

$shards = array(1,2);
foreach ($shards as $shardID) {
	Zotero_DB::query("DELETE FROM items", false, $shardID);
}

// TODO: clear MongoDB values
Z_Core::$Mongo->removeAll("creatorData");
Z_Core::$Mongo->removeAll("itemDataValues");

// Sample data for user 1
$itemObj = new Zotero_Item();
$itemObj->setField('libraryID', 1);
$itemObj->setField('key', "AAAA2222", false, true);
$itemObj->setField('itemTypeID', 2, false, true);
$itemObj->save();

// Sample data for user 2
$itemObj = new Zotero_Item();
$itemObj->setField('libraryID', 2);
$itemObj->setField('key', "BBBB2222", false, true);
$itemObj->setField('itemTypeID', 2, false, true);
$itemObj->save();

// Sample attachment for user 2
$itemObj = new Zotero_Item();
$itemObj->setField('libraryID', 2);
$itemObj->setField('key', "CCCC4444", false, true);
$itemObj->setField('itemTypeID', 14, false, true);
$itemID = $itemObj->save();

// Sample data for group 1
$itemObj = new Zotero_Item();
$itemObj->setField('libraryID', 3);
$itemObj->setField('key', "CCCC2222", false, true);
$itemObj->setField('itemTypeID', 2, false, true);
$itemObj->save();

// Sample attachment for group 1
$itemObj = new Zotero_Item();
$itemObj->setField('libraryID', 3);
$itemObj->setField('key', "CCCC3333", false, true);
$itemObj->setField('itemTypeID', 14, false, true);
$itemID = $itemObj->save();

?>
