#!/bin/sh
MASTER="mysql -h 127.0.0.1 -P 3306 -u root"
SLAVE="mysql -h 127.0.0.1 -P 3307 -u root"
MYSQLDUMP="mysqldump -h 127.0.0.1 -P 3306 -u root"

echo "STOP SLAVE;" | $SLAVE
echo "RESET SLAVE;" | $SLAVE

echo "DROP DATABASE IF EXISTS zoterotest1" | $SLAVE
echo "DROP DATABASE IF EXISTS zoterotest2" | $SLAVE
echo "DROP DATABASE IF EXISTS zoterotest_master" | $SLAVE
echo "DROP DATABASE IF EXISTS zoterotest_master" | $MASTER

echo "CREATE DATABASE zoterotest_master" | $MASTER
echo "CREATE DATABASE zoterotest_master" | $SLAVE
echo "CREATE DATABASE zoterotest1" | $SLAVE
echo "CREATE DATABASE zoterotest2" | $SLAVE

echo "DROP USER zoterotest0@localhost;" | $MASTER
echo "DROP USER zoterotestrepl@localhost;" | $MASTER
echo "DROP USER zoterotest1@localhost;" | $SLAVE
echo "DROP USER zoterotest2@localhost;" | $SLAVE

echo "CREATE USER zoterotest0@localhost IDENTIFIED BY 'pass0';" | $MASTER
echo "CREATE USER zoterotestrepl@localhost IDENTIFIED BY 'passrepl';" | $MASTER

echo "CREATE USER zoterotest1@localhost IDENTIFIED BY 'pass1';" | $SLAVE
echo "CREATE USER zoterotest2@localhost IDENTIFIED BY 'pass2';" | $SLAVE

echo "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON zoterotest_master.* TO zoterotest0@localhost;" | $MASTER
echo "GRANT SELECT, INSERT, DELETE ON zotero_www_test.* TO zoterotest0@localhost;" | $MASTER
echo "GRANT REPLICATION SLAVE ON *.* TO zoterotestrepl@localhost;" | $MASTER

echo "GRANT SELECT ON zoterotest_master.* TO zoterotest1@localhost;" | $SLAVE
echo "GRANT SELECT ON zoterotest_master.* TO zoterotest2@localhost;" | $SLAVE
echo "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON zoterotest1.* TO zoterotest1@localhost;" | $SLAVE
echo "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON zoterotest2.* TO zoterotest2@localhost;" | $SLAVE

$MASTER zoterotest_master < master.sql
$MASTER zoterotest_master < coredata.sql

echo "INSERT INTO shardHosts VALUES (1, '127.0.0.1', 3307, 'up');" | $MASTER zoterotest_master
echo "INSERT INTO shards VALUES (1, 1, 'zoterotest1', 'pass1', 'zoterotest1', 'up');" | $MASTER zoterotest_master
echo "INSERT INTO shards VALUES (2, 1, 'zoterotest2', 'pass2', 'zoterotest2', 'down');" | $MASTER zoterotest_master

# Initial users and groups for tests
echo "INSERT INTO libraries VALUES (1, 'user', '0000-00-00 00:00:00', 0, 1)" | $MASTER zoterotest_master
echo "INSERT INTO libraries VALUES (2, 'user', '0000-00-00 00:00:00', 0, 1)" | $MASTER zoterotest_master
echo "INSERT INTO libraries VALUES (3, 'group', '0000-00-00 00:00:00', 0, 1)" | $MASTER zoterotest_master
echo "INSERT INTO users VALUES (1, 1, 'testuser', '0000-00-00 00:00:00', '0000-00-00 00:00:00')" | $MASTER zoterotest_master
echo "INSERT INTO users VALUES (2, 2, 'testuser2', '0000-00-00 00:00:00', '0000-00-00 00:00:00')" | $MASTER zoterotest_master
echo "INSERT INTO groups VALUES (1, 3, 'Test Group', 'test_group', 'Private', 1, 'admins', 'all', 'members', '', '', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00')" | $MASTER zoterotest_master
echo "INSERT INTO groupUsers VALUES (1, 1, 'owner', '0000-00-00 00:00:00', '0000-00-00 00:00:00')" | $MASTER zoterotest_master
echo "DELETE FROM zotero_www_test.users" | $MASTER zoterotest_master
echo "INSERT INTO zotero_www_test.users VALUES (1, 'testuser', 'b7a875fc1ea228b9061041b7cec4bd3c52ab3ce3', 'test@zotero.org', NULL, 'member', NULL, NULL, NULL, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'testuser')" | $MASTER zoterotest_master
echo "INSERT INTO zotero_www_test.users VALUES (2, 'testuser2', 'fc707fc0b8c62cfeeafffde7273978d29d6d2374', 'test2@zotero.org', NULL, 'member', NULL, NULL, NULL, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 'testuser2')" | $MASTER zoterotest_master

echo "RESET MASTER;" | $MASTER
echo "CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=3306, MASTER_USER='zoterotestrepl', MASTER_PASSWORD='passrepl';" | $SLAVE
# Table list should match replicate-do-table list below
$MYSQLDUMP --master-data=1 zoterotest_master baseFieldMappings charsets creatorTypes fields groups groupUsers itemTypeCreatorTypes itemTypeFields itemTypes libraries storageFiles users | $SLAVE zoterotest_master

cat shard.sql | sed 's/`master`/`zoterotest_master`/g' | $SLAVE zoterotest1
cat shard.sql | sed 's/`master`/`zoterotest_master`/g' | $SLAVE zoterotest2
cat triggers.sql | sed 's/`master`/`zoterotest_master`/g' | $SLAVE zoterotest1
cat triggers.sql | sed 's/`master`/`zoterotest_master`/g' | $SLAVE zoterotest2

# Master my.cnf:
#
# [mysqld]
# server-id = 1
# log-bin=binary_log
#
# Slave my.cnf:
#
# [mysqld]
# server-id = 2
# port = 3307
# relay-log = relay_log
# replicate-do-table = zoterotest_master.baseFieldMappings
# replicate-do-table = zoterotest_master.charsets
# replicate-do-table = zoterotest_master.creatorTypes
# replicate-do-table = zoterotest_master.fields
# replicate-do-table = zoterotest_master.groups
# replicate-do-table = zoterotest_master.groupUsers
# replicate-do-table = zoterotest_master.itemTypeCreatorTypes
# replicate-do-table = zoterotest_master.itemTypeFields
# replicate-do-table = zoterotest_master.itemTypes
# replicate-do-table = zoterotest_master.libraries
# replicate-do-table = zoterotest_master.storageFiles
# replicate-do-table = zoterotest_master.users

echo "START SLAVE;" | $SLAVE

mongo zoterotest --eval 'db.dropDatabase()'
mongo zoterotest mongo_schema.js

./test_setup
