---
# Source: localstack/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack
  namespace: "default"
  labels:
    helm.sh/chart: localstack-0.6.0
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
