<?
define("Z_ERROR_GROUP_NAME_UNAVAILABLE", 10);
define("Z_ERROR_USER_NOT_GROUP_MEMBER", 11);
define("Z_ERROR_CANNOT_DELETE_GROUP_OWNER", 12);
define("Z_ERROR_INVALID_GROUP_TYPE", 13);
define("Z_ERROR_PUBLIC_GROUP_EXISTS", 14);
define("Z_ERROR_LIBRARY_ACCESS_DENIED", 15);
define("Z_ERROR_GROUP_DESCRIPTION_TOO_LONG", 16);
define("Z_ERROR_ITEM_NOT_FOUND", 17);
define("Z_ERROR_TAG_TOO_LONG", 18);
define("Z_ERROR_USER_NOT_FOUND", 19);
define("Z_ERROR_TAG_NOT_FOUND", 20);
define("Z_ERROR_CREATOR_NOT_FOUND", 21);
define("Z_ERROR_COLLECTION_NOT_FOUND", 22);
define("Z_ERROR_KEY_NAME_TOO_LONG", 23);
define("Z_ERROR_GROUP_QUOTA_SET_BELOW_USAGE", 24);
define("Z_ERROR_ARRAY_SIZE_MISMATCH", 25);
define("Z_ERROR_COLLECTION_TOO_LONG", 26);
define("Z_ERROR_TAG_LINKED_ITEM_NOT_FOUND", 27);
define("Z_ERROR_SHARD_UNAVAILABLE", 28);
define("Z_ERROR_SHARD_READ_ONLY", 29);
define("Z_ERROR_CITESERVER_INVALID_STYLE", 30);
define("Z_ERROR_INVALID_INPUT", 31);
define("Z_ERROR_OBJECT_LIBRARY_MISMATCH", 32);
define("Z_ERROR_LIBRARY_TIMESTAMP_ALREADY_USED", 33);
?>
