apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-dataserver-config
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  init.sh: {{ .Values.dataserverConfig.initSh | toYaml | indent 1 }}