apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-db-config
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  mariadb-databasename: {{ .Values.dbConfig.mariadbDatabasename | quote }}
  mariadb-user: {{ .Values.dbConfig.mariadbUser | quote }}