apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    apps: memcached
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.memcached.type }}
  selector:
    apps: zotprime-memcached
  ports:
	{{- .Values.memcached.ports | toYaml | nindent 2 -}}