apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-minio-config
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  minio-user: {{ .Values.minioConfig.minioUser | quote }}