apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-redis-config
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  redis.conf: {{ .Values.redisConfig.redisConf | toYaml | indent 1 }}