apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-redis-probes
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  liveness.sh: {{ .Values.redisProbes.livenessSh | toYaml | indent 1 }}
  readiness.sh: {{ .Values.redisProbes.readinessSh | toYaml | indent 1 }}