apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: streamserver-backendconfig
  namespace: zotprime
spec:
  timeoutSec: 3600
#  healthCheck:
#    checkIntervalSec: 30
#    timeoutSec: 20
#    healthyThreshold: 1
#    unhealthyThreshold: 3
#    type: HTTP
#    requestPath: /health
#    port: 81