apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataminio
  namespace: zotprime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo