apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: zotprime
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: uniuuu@myyahoo.com # ❗ Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          name: web-ingress
