apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-dataminio
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dataminio.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.dataminio.storageClass | quote }}