apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-db-secret
  labels:
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
data:
  secret-db.txt: {{ required "dbSecret.secretTxt is required" .Values.dbSecret.secretTxt }}
type: Opaque