apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    apps: elasticsearch
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticsearch.type }}
  selector:
    apps: zotprime-elasticsearch
  ports:
	{{- .Values.elasticsearch.ports | toYaml | nindent 2 -}}