apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    apps: minio
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.type }}
  clusterIP: 10.152.183.11
  selector:
    apps: zotprime-minio
  ports:
	{{- .Values.minio.ports | toYaml | nindent 2 -}}