apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    apps: redis
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    apps: zotprime-redis
  ports:
	{{- .Values.redis.ports | toYaml | nindent 2 -}}